In [345]:
import warnings
warnings.filterwarnings('ignore')
import numpy as np
import pandas as pd

In [346]:
df=pd.read_csv("titanic.csv")
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
5              6         0       3   
6              7         0       1   
7              8         0       3   
8              9         1       3   
9             10         1       2   
10            11         1       3   
11            12         1       1   
12            13         0       3   
13            14         0       3   
14            15         0       3   
15            16         1       2   
16            17         0       3   
17            18         1       2   
18            19         0       3   
19            20         1       3   
20            21         0       2   
21            22         1       2   
22            23         1       3   
23            24         1       1   
24            25         0       3   
25            26         1       3   
26            27         0       3   
27            28         0       1   
28            29         1       3   
29            30         0       3   
..           ...       ...     ...   
861          862         0       2   
862          863         1       1   
863          864         0       3   
864          865         0       2   
865          866         1       2   
866          867         1       2   
867          868         0       1   
868          869         0       3   
869          870         1       3   
870          871         0       3   
871          872         1       1   
872          873         0       1   
873          874         0       3   
874          875         1       2   
875          876         1       3   
876          877         0       3   
877          878         0       3   
878          879         0       3   
879          880         1       1   
880          881         1       2   
881          882         0       3   
882          883         0       3   
883          884         0       2   
884          885         0       3   
885          886         0       3   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
5                                     Moran, Mr. James    male   NaN      0   
6                              McCarthy, Mr. Timothy J    male  54.0      0   
7                       Palsson, Master. Gosta Leonard    male   2.0      3   
8    Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   
9                  Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1   
10                     Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                            Bonnell, Miss. Elizabeth  female  58.0      0   
12                      Saundercock, Mr. William Henry    male  20.0      0   
13                         Andersson, Mr. Anders Johan    male  39.0      1   
14                Vestrom, Miss. Hulda Amanda Adolfina  female  14.0      0   
15                    Hewlett, Mrs. (Mary D Kingcome)   female  55.0      0   
16                                Rice, Master. Eugene    male   2.0      4   
17                        Williams, Mr. Charles Eugene    male   NaN      0   
18   Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.0      1   
19                             Masselmani, Mrs. Fatima  female   NaN

In [347]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
PassengerId    891 non-null int64
Survived       891 non-null int64
Pclass         891 non-null int64
Name           891 non-null object
Sex            891 non-null object
Age            714 non-null float64
SibSp          891 non-null int64
Parch          891 non-null int64
Ticket         891 non-null object
Fare           891 non-null float64
Cabin          204 non-null object
Embarked       889 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.6+ KB


In [348]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [349]:
df.drop('Cabin',axis=1,inplace=True)

In [350]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [351]:
df.drop('PassengerId',axis=1,inplace=True)

In [352]:
df.drop('Name',axis=1,inplace=True)

In [353]:
df.drop('Ticket',axis=1,inplace=True)

In [354]:
df['Age'].fillna(method='bfill',inplace=True)

In [355]:
df['Embarked'].fillna(method='bfill',inplace=True)

In [356]:
a=pd.get_dummies(df['Embarked'],drop_first=True)
df=pd.concat([df,a],axis=1)
a.head()

Q  S
0  0  1
1  0  0
2  0  1
3  0  1
4  0  1

In [357]:
df.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Q           0
S           0
dtype: int64

In [358]:
df.drop('Embarked',axis=1,inplace=True)

In [359]:
from sklearn.preprocessing import LabelEncoder

In [360]:
le=LabelEncoder()

In [361]:
df['Sex']=le.fit_transform(df['Sex'])

In [362]:
df.skew()

Survived    0.478523
Pclass     -0.630548
Sex        -0.618921
Age         0.342346
SibSp       3.695352
Parch       2.749117
Fare        4.787317
Q           2.948778
S          -1.003362
dtype: float64

In [363]:
df.kurtosis()

Survived    -1.775005
Pclass      -1.280015
Sex         -1.620580
Age          0.213113
SibSp       17.880420
Parch        9.778125
Fare        33.398141
Q            6.710347
S           -0.995505
dtype: float64

In [364]:
df1=df[(df['Fare']>(np.mean(df['Fare'])-3*np.std(df['Fare']))) & (df['Fare']<(np.mean(df['Fare'])+2*np.std(df['Fare'])))]

In [365]:
df1.skew()

Survived    0.547883
Pclass     -0.760689
Sex        -0.687898
Age         0.354071
SibSp       3.757074
Parch       2.910165
Fare        1.868578
Q           2.864611
S          -1.053532
dtype: float64

In [366]:
df1.shape

(853, 9)

In [367]:
df1.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Q', 'S'], dtype='object')

In [368]:
from sklearn.model_selection import train_test_split

In [369]:
X=df1[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare', 'Q', 'S']]
y=df1['Survived']

In [370]:
X_train,X_test,y_train,y_test=train_test_split(X,y,train_size=0.7,test_size=0.3,random_state=101)

In [371]:
from sklearn.preprocessing import StandardScaler

In [372]:
scaler=StandardScaler()

In [373]:
X_train[['Fare','Age']]=scaler.fit_transform(X_train[['Fare','Age']])
X_test[['Fare','Age']]=scaler.transform(X_test[['Fare','Age']])
X_train_scaled=X_train
X_test_scaled=X_test
X_train.head()

Pclass  Sex       Age  SibSp  Parch      Fare  Q  S
564       3    0 -0.386615      0      0 -0.653110  0  1
784       3    1 -0.315675      0      0 -0.695505  0  1
753       3    1 -0.457554      0      0 -0.659648  0  1
692       3    1 -0.315675      0      0  1.400720  0  1
625       1    1  2.238156      0      0  0.375836  0  1

In [374]:
type(X_test)

pandas.core.frame.DataFrame

In [375]:
type(X_train)

pandas.core.frame.DataFrame

In [376]:
from sklearn.linear_model import LogisticRegression
lgr=LogisticRegression()

In [377]:
from sklearn.feature_selection import RFE
rfe=RFE(lgr,5)

In [378]:
rfe=rfe.fit(X_train_scaled,y_train)

In [379]:
rfe.support_

array([ True,  True,  True,  True, False,  True, False, False])

In [380]:
rfe.ranking_

array([1, 1, 1, 1, 3, 1, 4, 2])

In [381]:
list(zip(X_train.columns,rfe.support_,rfe.ranking_))

[('Pclass', True, 1),
 ('Sex', True, 1),
 ('Age', True, 1),
 ('SibSp', True, 1),
 ('Parch', False, 3),
 ('Fare', True, 1),
 ('Q', False, 4),
 ('S', False, 2)]

In [382]:
selected_col=X_train_scaled.columns[rfe.support_]

In [383]:
type(selected_col)

pandas.core.indexes.base.Index

In [384]:
selected_col

Index(['Pclass', 'Sex', 'Age', 'SibSp', 'Fare'], dtype='object')

In [385]:
X_train_scaled_rfe=X_train_scaled[selected_col]
type(X_train_scaled_rfe)

pandas.core.frame.DataFrame

In [398]:
lgr.fit(X_train_scaled_rfe,y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [399]:
import statsmodels.api as sm

In [400]:
X_train_scaled_rfe_sm=sm.add_constant(X_train_scaled_rfe)

In [401]:
lgmod=sm.GLM(y_train,X_train_scaled_rfe_sm,family=sm.families.Binomial()).fit()

In [402]:
print(lgmod.summary())

                 Generalized Linear Model Regression Results                  
Dep. Variable:               Survived   No. Observations:                  597
Model:                            GLM   Df Residuals:                      591
Model Family:                Binomial   Df Model:                            5
Link Function:                  logit   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -264.24
Date:                Thu, 12 Sep 2019   Deviance:                       528.49
Time:                        12:28:30   Pearson chi2:                     585.
No. Iterations:                     5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          3.3785      0.503      6.714      0.0

In [403]:
from statsmodels.stats.outliers_influence import variance_inflation_factor

In [404]:
vif=pd.DataFrame()
vif['Features']=X_train_scaled_rfe_sm.columns
vif['VIF']=[variance_inflation_factor(X_train_scaled_rfe_sm.values,i) for i in range(X_train_scaled_rfe_sm.shape[1])]
vif["VIF"]=round(vif["VIF"],2)
vif=vif.sort_values(by="VIF",ascending=False)
vif

Features    VIF
0    const  21.81
5     Fare   2.36
1   Pclass   2.21
4    SibSp   1.40
3      Age   1.15
2      Sex   1.06

In [405]:
y_pred_sm=lgmod.predict(X_train_scaled_rfe_sm)

In [406]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [407]:
print(' Accuracy Score:\n')
print(accuracy_score(y_train,y_pred_sm.round()))

 Accuracy Score:

0.7922948073701842


In [408]:
print("confusion Matrix:\n\n",confusion_matrix(y_train,y_pred_sm.round()))

confusion Matrix:

 [[341  49]
 [ 75 132]]


In [409]:
X_test_scaled_rfe=X_test[X_train_scaled_rfe.columns]
X_test_scaled_rfe.head()

Pclass  Sex       Age  SibSp      Fare
252       1    1  2.309096      0  0.131186
724       1    1 -0.173795      1  1.256757
586       2    1  1.245000      0 -0.358469
878       3    1  1.883457      0 -0.659648
788       3    1 -2.018229      1 -0.122121

In [410]:
y_pred_lgr_test=lgr.predict(X_test_scaled_rfe)

In [411]:
print(' Accuracy Score:\n')
print(accuracy_score(y_test,y_pred_lgr_test.round()))

 Accuracy Score:

0.79296875


In [412]:
print("confusion Matrix:\n\n",confusion_matrix(y_test,y_pred_lgr_test.round()))

confusion Matrix:

 [[136  13]
 [ 40  67]]


In [413]:
print("\n\nClassification Report:\n",classification_report(y_test,y_pred_lgr_test))



Classification Report:
               precision    recall  f1-score   support

           0       0.77      0.91      0.84       149
           1       0.84      0.63      0.72       107

    accuracy                           0.79       256
   macro avg       0.81      0.77      0.78       256
weighted avg       0.80      0.79      0.79       256

