In [5]:
import numpy as np
li=[1,2,3,4,5]
a=np.array(li)
type(a)

numpy.ndarray

In [6]:
a

array([1, 2, 3, 4, 5])

In [7]:
print(a)

[1 2 3 4 5]


In [8]:
a.ndim # 1-dimention

1

In [9]:
a.shape

(5,)

In [10]:
a.dtype

dtype('int32')

In [2]:
import numpy
numpy.

SyntaxError: invalid syntax (<ipython-input-2-774047a72a69>, line 2)

In [11]:
a=np.array(['p','o',1,2])
a

array(['p', 'o', '1', '2'], dtype='<U1')

In [12]:
li=[1,2,3,4,5]
a=np.array([li])
print(a)



[[1 2 3 4 5]]


In [13]:
a.ndim #2D

2

In [14]:
a.shape

(1, 5)

In [20]:
b=np.array([[1,2,3],[2,3,4]])
print(b)
print(b.ndim)
b.shape
b.dtype

[[1 2 3]
 [2 3 4]]
2


dtype('int32')

In [16]:
print(b.ndim)

2


In [17]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [18]:
b.shape

(2, 3)

In [19]:
b.dtype

dtype('int32')

In [31]:
b=np.array([[1,2],[2,3,4]])
print(b)
b.ndim
b.shape

[list([1, 2]) list([2, 3, 4])]


(2,)

In [28]:
b=np.array([[[1,2,3],[2,3,4]],[[5,6,7],[8,9,9]]])
print(b)
print(b.ndim)
# 2row and 3 col in xy axis 2row and 3 col in z axis 
b.shape

[[[1 2 3]
  [2 3 4]]

 [[5 6 7]
  [8 9 9]]]
3


(2, 2, 3)

In [36]:
d=np.array([[2.4,3.5,4]])
d.dtype

dtype('float64')

In [34]:
c=np.array(['po','mk'])
c.dtype

dtype('<U2')

In [38]:
e=np.array([2.4,5.4,6,7],dtype=int) #it take everyhing as int where we explicitly done my us
e.dtype

dtype('int32')

In [44]:
# z=np.array([5,6])
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [45]:
# z=np.array([5,6,4,5])
z=np.ones(5)#1D
z

array([1., 1., 1., 1., 1.])

In [46]:
z=np.zeros((3,4))#2D
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [49]:
z=np.zeros(((3,4,5)))#3D 4and5 is row and col 3 is 3d one
z

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [51]:
p=np.arange(10)
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
p=p.reshape(5,2)
p

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [54]:
p=np.arange(12)
p=p.reshape(2,2,3)
p

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [55]:
p=np.arange(10,101,5)
p

array([ 10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,
        75,  80,  85,  90,  95, 100])

In [56]:
p=np.arange(10,101,5)
p.shape #to find number of elements

(19,)

In [57]:
p=np.arange(12).reshape(3,4)
p

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
q=np.arange(100,200,5).reshape(4,5)
q

array([[100, 105, 110, 115, 120],
       [125, 130, 135, 140, 145],
       [150, 155, 160, 165, 170],
       [175, 180, 185, 190, 195]])

In [62]:
q=np.arange(100,200,5).reshape(4,5)
q+2

array([[102, 107, 112, 117, 122],
       [127, 132, 137, 142, 147],
       [152, 157, 162, 167, 172],
       [177, 182, 187, 192, 197]])

In [64]:
q=np.arange(100,200,5).reshape(4,5)
q-2

array([[ 98, 103, 108, 113, 118],
       [123, 128, 133, 138, 143],
       [148, 153, 158, 163, 168],
       [173, 178, 183, 188, 193]])

In [65]:
q=np.arange(100,200,5).reshape(4,5)
q*2

array([[200, 210, 220, 230, 240],
       [250, 260, 270, 280, 290],
       [300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390]])

In [66]:
q=np.arange(100,200,5).reshape(4,5)
q/2

array([[50. , 52.5, 55. , 57.5, 60. ],
       [62.5, 65. , 67.5, 70. , 72.5],
       [75. , 77.5, 80. , 82.5, 85. ],
       [87.5, 90. , 92.5, 95. , 97.5]])

In [67]:
q=np.arange(100,200,5).reshape(4,5)
q%2

array([[0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0],
       [1, 0, 1, 0, 1]], dtype=int32)

In [68]:
q=np.arange(100,200,5).reshape(4,5)
q**2

array([[10000, 11025, 12100, 13225, 14400],
       [15625, 16900, 18225, 19600, 21025],
       [22500, 24025, 25600, 27225, 28900],
       [30625, 32400, 34225, 36100, 38025]], dtype=int32)

In [69]:
q=np.arange(100,200,5).reshape(4,5)
print(q)
print(q+2)
print(q-2)
print(q*2)
print(q/2)
print(q%2)
print(q**2)

[[100 105 110 115 120]
 [125 130 135 140 145]
 [150 155 160 165 170]
 [175 180 185 190 195]]
[[102 107 112 117 122]
 [127 132 137 142 147]
 [152 157 162 167 172]
 [177 182 187 192 197]]
[[ 98 103 108 113 118]
 [123 128 133 138 143]
 [148 153 158 163 168]
 [173 178 183 188 193]]
[[200 210 220 230 240]
 [250 260 270 280 290]
 [300 310 320 330 340]
 [350 360 370 380 390]]
[[50.  52.5 55.  57.5 60. ]
 [62.5 65.  67.5 70.  72.5]
 [75.  77.5 80.  82.5 85. ]
 [87.5 90.  92.5 95.  97.5]]
[[0 1 0 1 0]
 [1 0 1 0 1]
 [0 1 0 1 0]
 [1 0 1 0 1]]
[[10000 11025 12100 13225 14400]
 [15625 16900 18225 19600 21025]
 [22500 24025 25600 27225 28900]
 [30625 32400 34225 36100 38025]]


In [71]:
x=np.arange(16).reshape(3,4)
x

ValueError: cannot reshape array of size 16 into shape (3,4)

In [72]:
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [76]:
x=np.arange(16).reshape(4,4)
y=np.hsplit(x,2)
print(y)

[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])]


In [78]:
x=np.arange(16).reshape(4,4)
y=np.vsplit(x,2)
y

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [84]:
x=np.arange(16).reshape(4,4)
y=np.arange(16).reshape(4,4)
z=np.hstack((x,y))
z1=np.vstack((x,y))
print(z)
print(z1)

[[ 0  1  2  3  0  1  2  3]
 [ 4  5  6  7  4  5  6  7]
 [ 8  9 10 11  8  9 10 11]
 [12 13 14 15 12 13 14 15]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [87]:
np.random.rand()#gives random num from 0 to 1

0.23318444006299222

In [89]:
a=np.random.rand(10)
a

array([0.19549787, 0.36484573, 0.09331777, 0.17875136, 0.80823346,
       0.05216003, 0.39848329, 0.39257162, 0.63865494, 0.97724156])

In [91]:
a=np.random.randint(10)
a

3

In [93]:
a=np.random.randint(10,20)
a

19

In [96]:
a=np.random.randint(10,20,10)
a

array([14, 15, 17, 16, 12, 13, 10, 12, 10, 19])

In [97]:
a=np.random.randint(10,20,10).reshape(5,2)
a

array([[14, 15],
       [14, 17],
       [17, 19],
       [15, 14],
       [17, 10]])

In [103]:
#normally distributed from - to + range
a=np.random.randn(10)
a

array([ 0.75595854,  0.49298571,  2.95732534, -1.20790071, -0.83340433,
       -0.32184967, -2.16953532,  0.07952168, -1.41444544, -1.30785319])

In [104]:
a=np.random.randn(10).reshape(5,2)
a

array([[-0.45273558,  0.19680566],
       [ 0.42203336,  0.04099913],
       [ 1.59204327,  1.34137053],
       [ 0.1040796 , -1.04715045],
       [ 0.83241493,  0.66917779]])

In [109]:
z=np.floor(4.6)
z

4.0

In [110]:
z=np.ceil(4.2)
z

5.0

In [107]:
z=np.round(4.7)
z

5.0

In [122]:
a=np.array([1,2,3])
b=a
b[1]=10
print('b=',b)
print('a=',a) #'a' as changed so use copy()

b= [ 1 10  3]
a= [ 1 10  3]


In [123]:
a=np.array([1,2,3])
b=a.copy()
b[1]=10
print('b=',b)
print('a=',a)#copy is used so 'a' as not changed

b= [ 1 10  3]
a= [1 2 3]


In [124]:
np.linspace(1,10,10) #it is giving equally spaced num between that range inclusive

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [125]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [127]:
np.linspace(1,10,20).reshape(5,4)

array([[ 1.        ,  1.47368421,  1.94736842,  2.42105263],
       [ 2.89473684,  3.36842105,  3.84210526,  4.31578947],
       [ 4.78947368,  5.26315789,  5.73684211,  6.21052632],
       [ 6.68421053,  7.15789474,  7.63157895,  8.10526316],
       [ 8.57894737,  9.05263158,  9.52631579, 10.        ]])

In [132]:
a=np.array([1,2,3])
print(a.min())#gives the value of min num
print(a.max())#gives the value of min num
print(a.argmin())#gives the index of min num
print(a.argmax())#gives the index of max num

1
3
0
2


In [133]:
a=np.array([1,2,3,0])
print(a.min())#gives the value of min num
print(a.max())#gives the value of min num
print(a.argmin())#gives the index of min num
print(a.argmax())#gives the index of max num

0
3
3
2


In [134]:
a=np.array([1,2,3,0])
np.all(a)

False

In [136]:
a=np.array([1,2,3])
np.all(a)

True

In [137]:
a=np.array([1,2,3])
np.any(a)

True

In [138]:
a=np.array([1,2,3,0])
np.any(a)

True

In [139]:
a=np.array([0,0,0])
np.any(a)

False

In [140]:
a=np.array([1+2j,5+8j,2+4j])
a

array([1.+2.j, 5.+8.j, 2.+4.j])

In [141]:
a=np.array([1+2j,5+8j,2+4j,5j])
a

array([1.+2.j, 5.+8.j, 2.+4.j, 0.+5.j])

In [142]:
a=np.array([1+2j,5+8j,2+4j,5j])
np.isreal(a)

array([False, False, False, False])

In [143]:
a=np.array([1+2j,5+8j,2+4j,5j])
np.iscomplex(a)

array([ True,  True,  True,  True])

In [144]:
a=np.array([1,2,2])
np.isreal(a)

array([ True,  True,  True])

In [145]:
a=np.array([1,2,2])
np.iscomplex(a)

array([False, False, False])

In [148]:
a=np.array([1,2,2])
b=np.array([1,1])
np.dot(a,b)

ValueError: shapes (3,) and (2,) not aligned: 3 (dim 0) != 2 (dim 0)

In [149]:
a=np.array([1,2,2])
b=np.array([1,1,1])# implicitly it takes row*col
np.dot(a,b)

5

In [152]:
a=np.array([[1,2],[1,2]])
b=np.array([[1,1],[1,2]])#row and col must be same
np.dot(a,b)

array([[3, 5],
       [3, 5]])

In [154]:
a=np.array([[1,2],[1,2],[1,1]])
b=np.array([[1,1],[1,2],[1,1]])#row and col must be same(squre matrix)
np.dot(a,b)

ValueError: shapes (3,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [153]:
a=np.array([[1,2,1],[1,1,2],[1,1,1]])
b=np.array([[1,1,1],[1,2,1],[1,1,1]])
np.dot(a,b)

array([[4, 6, 4],
       [4, 5, 4],
       [3, 4, 3]])

In [155]:
a=np.array([[1,2],[1,2]])
b=np.array([[1,1],[1,2]])
np.greater(a,b)

array([[False,  True],
       [False, False]])

In [156]:
a=np.array([[1,2],[1,2]])
b=np.array([[1,1],[1,2]])
np.greater_equal(a,b)

array([[ True,  True],
       [ True,  True]])

In [158]:
a=np.array([[1,2],[1,2]])
b=np.array([[1,1],[1,2]])
a+b
a-b

array([[0, 1],
       [0, 0]])

In [159]:
a=np.random.rand(36).reshape(6,6)
a

array([[0.17332335, 0.34089197, 0.32318841, 0.15003565, 0.33976061,
        0.43381594],
       [0.80584189, 0.51582073, 0.71806194, 0.00347917, 0.26170611,
        0.07346793],
       [0.01275846, 0.83893752, 0.27176073, 0.60588233, 0.55330104,
        0.21771433],
       [0.39068991, 0.86761538, 0.42583412, 0.69578879, 0.10548117,
        0.57019146],
       [0.6100784 , 0.78729188, 0.41590733, 0.41249998, 0.37346996,
        0.16767964],
       [0.98049137, 0.48201411, 0.55762519, 0.96382632, 0.93392199,
        0.06859377]])

In [160]:
a=100*np.random.rand(36).reshape(6,6)
a

array([[42.10381691, 66.9174302 , 92.01750704, 81.69261773,  7.43942807,
        11.82291297],
       [35.36952306, 22.65859393, 73.94370412, 30.25668005, 45.16454721,
        33.05734178],
       [70.69828805, 57.627182  , 79.51263254, 75.45374605, 17.9981451 ,
        27.05763213],
       [51.30156213, 80.22557903, 44.20018074, 85.64816388, 31.28259315,
        65.1959928 ],
       [56.37383985, 17.22123765, 97.93364583, 30.0161455 , 35.09872483,
        13.50580872],
       [91.95052065, 49.59105632, 92.54871413, 81.2851512 , 52.37106693,
        77.99330821]])

In [163]:
a=np.round(100*np.random.rand(36).reshape(6,6))
a

array([[44., 77., 38., 16., 77., 69.],
       [26., 61., 30., 81., 21., 38.],
       [83., 99., 13., 96., 91., 20.],
       [82., 74., 83.,  7., 28., 60.],
       [54., 55., 91., 23., 45., 25.],
       [ 9., 52., 99., 70., 72., 76.]])

In [166]:
a=np.floor(100*np.random.rand(36).reshape(6,6))
a

array([[39., 27., 46., 60., 99., 40.],
       [60., 29., 28., 50., 26., 75.],
       [ 9., 77., 63., 41., 51., 25.],
       [41., 85., 86., 85., 28., 98.],
       [71., 83., 67., 24.,  4., 24.],
       [24., 79., 79.,  4., 48., 70.]])

In [172]:
a=np.floor(np.random.rand(36).reshape(6,6))
a

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [168]:
a=np.floor(100*np.random.rand(36).reshape(6,6))
a.dtype

dtype('float64')

In [175]:
a=np.array([2,2,3])
np.ceil(np.sqrt(a))

array([2., 2., 2.])

In [176]:
a=np.floor(100*np.random.rand(36).reshape(6,6))
np.exp(a)

array([[1.48413159e+02, 5.98741417e+04, 6.23514908e+27, 3.83100800e+22,
        1.62754791e+05, 4.85165195e+08],
       [9.25378173e+29, 1.04137594e+23, 2.75851345e+33, 6.83767123e+30,
        9.01762841e+39, 9.01762841e+39],
       [5.32048241e+11, 5.98741417e+04, 1.37338298e+32, 1.28516001e+19,
        1.25236317e+29, 3.93133430e+12],
       [3.58491285e+09, 2.29378316e+27, 4.85165195e+08, 1.73927494e+18,
        8.43835667e+26, 3.93133430e+12],
       [2.98095799e+03, 4.72783947e+18, 1.22040329e+39, 2.03828107e+34,
        3.73324200e+32, 8.22301271e+36],
       [4.31123155e+15, 5.32048241e+11, 2.09165950e+24, 6.07603023e+37,
        9.88903032e+42, 1.50609731e+35]])

In [177]:
a=np.floor(100*np.random.rand(36).reshape(6,6))
np.sin(a)

array([[ 0.10598751,  0.39592515,  0.52908269,  0.96836446,  0.42016704,
        -0.64353813],
       [ 0.99060736, -0.17607562, -0.30481062, -0.13235175, -0.99177885,
         0.74511316],
       [-0.98803162, -0.7568025 , -0.28790332, -0.38778164, -0.96139749,
         0.37960774],
       [-0.17607562,  0.74511316, -0.89792768,  0.98358775,  0.56610764,
         0.27090579],
       [-0.30481062, -0.62988799, -0.40403765, -0.85551998,  0.99952016,
        -0.99388865],
       [ 0.01770193, -0.99999021, -0.96139749, -0.98803162, -0.28790332,
        -0.99177885]])

In [183]:
a=np.array([1,2,2])
b=np.array([1,1,1])
np.matmul(a,b)

5

In [184]:
np.log(a)

array([0.        , 0.69314718, 0.69314718])

In [185]:
np.max(a)

2

In [194]:
a=np.array([[1,2],[6,5]])
np.linalg.inv(a)

array([[-0.71428571,  0.28571429],
       [ 0.85714286, -0.14285714]])

In [195]:
a=np.array([[1,2],[6,5]])
np.linalg.det(a)

-6.999999999999999

In [197]:
b=np.array([[1,2,3],[4,5,6],[9,8,7]])
b[1,2]

6

In [198]:
b[1:]

array([[4, 5, 6],
       [9, 8, 7]])

In [199]:
b[1:2]

array([[4, 5, 6]])

In [200]:
b[1:2,1:2]

array([[5]])

In [203]:
a=np.arange(36).reshape(6,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [220]:
a[1:2,1:2]
a[1,1]

7

In [206]:
a[2:4,2:5]

array([[14, 15, 16],
       [20, 21, 22]])

In [215]:
a[0:1[4:5],2:6[2:6]

SyntaxError: unexpected EOF while parsing (<ipython-input-215-efac952b33cc>, line 1)

In [218]:
a[[0,4],2:]

array([[ 2,  3,  4,  5],
       [26, 27, 28, 29]])

In [219]:
a[2:,[0,1,5]]

array([[12, 13, 17],
       [18, 19, 23],
       [24, 25, 29],
       [30, 31, 35]])